### ISSUE TITLE
Invalid float

### ISSUE THREAD

**Issue by jtpesone** [gtkfi/GisSOM#24]
The input file gives an Invalid Float error when pressing Run in the SOM computation window.
Input file, input data parameters, SOM parameters and error message are at

[https://gtkfi.sharepoint.com/sites/DroneSOM/Jaetut%20asiakirjat/Forms/AllItems.aspx?RootFolder=%2Fsites%2FDroneSOM%2FJaetut%20asiakirjat%2FWP5%20%2D%20Drone%20geophysical%20data%20integration%20software%2FBugRelatedData%2FIssue24&FolderCTID=0x01200080527C223F58B049BCBE7924DEE86A52]

**Comment by jtpesone** [comment]
This problem was due the inproper Windows regional settings. Decimal separator should be set to a dot ('.') and list separator to a comma (','). It would be more user friendly, if this could be handled by the software.

**Comment by jtorppa** [comment]
This problem was due the inproper Windows regional settings. Decimal separator should be set to a dot ('.') and list separator to a comma (','). It would be more user friendly, if this could be handled by the software.
