### ISSUE TITLE
nextsom_wrap.exe --scale0: invalid float value '0.1'

### ISSUE THREAD

**Issue by ngadiy** [gtkfi/GisSOM#30]
Hi,
I have a csv grid data, formatted as indicated in the user guide. When I download the data, I can correctly visualize the different variables. However, it keeps failing to complete the SOM run.
The first error thrown is this one: nextsom_wrap.exe --scale0: invalid float value '0.1'

**Comment by jtpesone** [comment]
This is probably caused by your Windows Regional number settings. Please, change your decimal separator to  a dot (".") and list separator to comma (","), and this should work.
Please let us know if this workaround solved the problem. We will fix the issue later.
